### ISSUE TITLE
Command line argument to specify the config file

### ISSUE THREAD

**Issue by leoheck** [johnbeard/kiplot#17]
@set-soft

Does your fork of the Kiplot accept this?

![image](https://user-images.githubusercontent.com/1277920/83931528-9a4c7100-a773-11ea-85cf-cdf21339b84c.png)

If not, do you mind in getting this feature from here?

**Comment by leoheck** [comment]
It looks like it has this `-c` flag
but something is strange since I have this file `board.kiplot.yaml`

![image](https://user-images.githubusercontent.com/1277920/83931633-1b0b6d00-a774-11ea-9bea-0c6c3c44276a.png)

did you docker change recently ar kiplot inside of it?

**Comment by set-soft** [comment]
The -c option was inherited from the parent project.
My fork looks for "*.kiplot.yaml", and if one or more files matches it takes the first match and uses it.
But be careful "board.yml" won't match. 
You can always use the explicit -c option.

**Comment by leoheck** [comment]
Got it, `*.kiplot.yaml` will be the first thing the script is going to look for.

Now, I am using this `-c kiplot.yml` since it is more explicit.

It was working during some tests, and when I made a new test in another branch, I got the image from the lats post. This is why I started this issue report in the first place. I have two actions so I was looking at the wrong one.
